image: rafaadail/php-ci:7.4

pipelines:
  develop:
    - step:
        name: Run PHP CI checks
        script:
          - php -v
          - composer --version
          - composer install --no-interaction --prefer-dist
          - php artisan test || true
