pipelines:
  branches:
    develop:
      - step:
          image: rafaadail/php-ci:7.4
          name: Run PHP CI checks
          script:
            - php -v
            - composer --version
            - composer install --no-interaction --prefer-dist
            - php artisan test || true
    main:
      - step:
          image: rafaadail/php-ci:7.4
          name: CI / Deploy - Production
          script:
            - composer install --no-dev